name: hakawati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  cloud_firestore: ^6.1.0
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  device_info_plus: ^12.3.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.0.0
  font_awesome_flutter: ^10.7.0
  get_it: ^9.2.0
  google_sign_in: ^6.3.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/lang/
    - assets/images/

  fonts:
    - family: Winter Drink
      fonts:
        - asset: assets/fonts/winter_drink/winter_drink.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
          weight: 300

    - family: Lalezar
      fonts:
        - asset: assets/fonts/lalezar/Lalezar-Regular.ttf

    - family: Marhey
      fonts:
        - asset: assets/fonts/marhey/Marhey-Bold.ttf
          weight: 700
        - asset: assets/fonts/marhey/Marhey-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/marhey/Marhey-Medium.ttf
          weight: 500
        - asset: assets/fonts/marhey/Marhey-Regular.ttf
          weight: 400
        - asset: assets/fonts/marhey/Marhey-Light.ttf
          weight: 300
